// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOv4JWeNdsQhCJXRHKCXxr0qSdl3_Lwl8',
    appId: '1:456351347186:web:0afab89c89ba1811c1bb6b',
    messagingSenderId: '456351347186',
    projectId: 'finance-1531b',
    authDomain: 'finance-1531b.firebaseapp.com',
    storageBucket: 'finance-1531b.firebasestorage.app',
    measurementId: 'G-3M0Q06EH76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR6HhlfESxL_H1QenDC19R7-tv9d1PrQI',
    appId: '1:456351347186:android:00eab3890a0f3504c1bb6b',
    messagingSenderId: '456351347186',
    projectId: 'finance-1531b',
    storageBucket: 'finance-1531b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJe7dfYRtEiOZGaiGK18-c5eayCQa_eA',
    appId: '1:456351347186:ios:c1e5e0fa816d354dc1bb6b',
    messagingSenderId: '456351347186',
    projectId: 'finance-1531b',
    storageBucket: 'finance-1531b.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJe7dfYRtEiOZGaiGK18-c5eayCQa_eA',
    appId: '1:456351347186:ios:c1e5e0fa816d354dc1bb6b',
    messagingSenderId: '456351347186',
    projectId: 'finance-1531b',
    storageBucket: 'finance-1531b.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOv4JWeNdsQhCJXRHKCXxr0qSdl3_Lwl8',
    appId: '1:456351347186:web:5c13f380c4cfeca5c1bb6b',
    messagingSenderId: '456351347186',
    projectId: 'finance-1531b',
    authDomain: 'finance-1531b.firebaseapp.com',
    storageBucket: 'finance-1531b.firebasestorage.app',
    measurementId: 'G-T7Z9BRRENZ',
  );
}
